export const opcionesMenu=[ { texto: "Escapadas vacacionales", enlace: "#" },
{ texto: "Escapadas fin de semana", enlace: "#" },
{ texto: "Viajes Nacionales", enlace: "#" },
{ texto: "Viajes Internacionales", enlace: "#" },
{ texto: "Ofertas especiales", enlace: "#containerContenedorMainInferior" },
{ texto: "Experiencias unicas", enlace: "#" },
{ texto: "Contacto", enlace: "#" },
{ texto: "Preguntas Frecuentes (FAQ)", enlace: "#" },
{ texto: "Sobre Nosotros", enlace: "#" },
{ texto: "Ajustes", enlace: "#" }]