export const opcionesMenu=[ { texto: "Viajes más populares", enlace: "/mostVisited" },
{ texto: "Escapadas fin de semana", enlace: "#" },
{ texto: "Viajes Nacionales", enlace: "#" },
{ texto: "Viajes Internacionales", enlace: "#" },
{ texto: "Ofertas especiales", enlace: "/#containerContenedorMainInferior" },
{ texto: "Experiencias romanticas", enlace: "/#containerContenedorMainInferior" },
{ texto: "Experiencias unicas", enlace: "#" },
{ texto: "Contacto", enlace: "/contacto" },
{ texto: "Preguntas Frecuentes (FAQ)", enlace: "#" },
{ texto: "Sobre Nosotros", enlace: "#" },
{ texto: "Ajustes", enlace: "#" }]